// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
  interface Window {
    __TAURI_INVOKE__<T>(
      cmd: string,
      args?: Record<string, unknown>
    ): Promise<T>;
  }
}

const invoke = window.__TAURI_INVOKE__;

export function helloTauri() {
  return invoke<string>('hello_tauri');
}

export function hash256sum(hashInput: string) {
  return invoke<string>('hash256sum', { hashInput });
}
