#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# If not using pnpm, switch to your package manager
npx lint-staged

cd src-tauri
cargo clippy --all --tests -- -W clippy::nursery -W clippy::pedantic -A clippy::module-name-repetitions -D clippy::unwrap_used 
cargo test --all